# general
batch_size: 512
num_workers: 2
token_path: /work/ga97/a97002/GRU_VAE/data/SFL_tokens.txt
SFL: true

# model architecture
embedding_dim: 256
enc_gru_layer: [512, 1024, 2048]
latent_dim: 512
dec_gru_layer: [512,1024,2048]

# train
epochs: 100
plot: true
dropout: 0.1
lr: 5.0e-6
gamma: 0.95
patience: 10
beta: 0
buckets_min: 20
buckets_max: 200
buckets_step: 10
train_data: /work/ga97/a97002/GRU_VAE/data/train.csv
valid_data: /work/ga97/a97002/GRU_VAE/data/val_100k.csv

# inference
maxlen: 1000