# general
batch_size: 128
num_workers: 2
token_path: /work/ga97/a97002/GRU_VAE/data/tokens.txt
SFL: false

# model architecture
embedding_dim: 256 # equal to latent dim
n_positions: 500 # equal to max length
n_layer: 8
n_head: 8
layer_norm_epsilon: 1.0e-5

# train
steps: 5000
plot: true
dropout: 0.1
max_lr: 2.0e-3
warmup: 12000
patience_step: 20000
buckets_min: 20
buckets_max: 200
buckets_step: 10
train_data: /work/ga97/a97002/GRU_VAE/data/train.csv
valid_data: /work/ga97/a97002/GRU_VAE/data/val_100k.csv
valid_step_range: 1000
beta: 0