# general
batch_size: 1024
num_workers: 2
token_path: ../tokens/normal_tokens.txt
SFL: false
seed: 123

# model architecture
embedding_dim: 128
enc_gru_layer: [256,512,1024]
latent_dim: 256
dec_gru_layer: [256,512,1024]

# train
steps: 500000
plot: true
dropout: 0.1
max_lr: 1.0e-1
warmup: 8000
patience_step: 10000
beta: 1.0
buckets_min: 20
buckets_max: 150
buckets_step: 10
train_data: /path/to/train.csv
valid_data: /path/to/valid.csv
valid_step_range: 500

# inference
maxlen: 500