# general
batch_size: 1024
num_workers: 2
token_path: /work/ga97/a97002/GRU_VAE/data_zinc/SFL_tokens.txt
SFL: true
seed: 123

# model architecture
embedding_dim: 128
enc_gru_layer: [256,512,1024]
latent_dim: 256
dec_gru_layer: [256,512,1024]

# train
steps: 500000
plot: true
dropout: 0.1
max_lr: 1.0e-1
warmup: 8000
patience_step: 10000
beta: 0.01
buckets_min: 20
buckets_max: 150
buckets_step: 10
train_data: /work/ga97/a97002/GRU_VAE/data_zinc/train.csv
valid_data: /work/ga97/a97002/GRU_VAE/data_zinc/test.csv
valid_step_range: 500

# inference
maxlen: 500